language: python
cache: pip

jobs:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: pypy3

install:
 - pip install pycodestyle pyflakes

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
