dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev

install:
 - pip install --upgrade pip
 - pip install --upgrade black flake8

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .
