language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
 - pip install --upgrade pip
 - pip install --upgrade black flake8

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .
